### ISSUE TITLE
angular position

### ISSUE THREAD

**Issue by aysegulucar2016** [sayantanauddy/hierarchical_bipedal_controller#1]
What are angular position of robot, alpha ? I cant see an expression of alpha beta and gamma in text. Did you use imu sensor? imu includes angular velocity, poziiton and acceleration?

Are torso orientation equal to pitch angle?

**Comment by sayantanauddy** [comment]
Alpha is the orientation of the torso about the x-axis. On the physical robot this value (and beta and gamma) will be calculated using the IMU but in the simulation these have been obtained directly from the simulator. 

The torso orientation that is of importance here is the yaw angle (around the z-axis).
