### ISSUE TITLE
About downloading files

### ISSUE THREAD

**Issue by shaosb** [sayantanauddy/hierarchical_bipedal_controller#2]
hi,i am interested about your program,but there is some problems
when i run 
git clone https://git.informatik.uni-hamburg.de/wtmstaff/MScThesis_SayantanAuddy_2017_NICOOscillatorWalking.git
it point me that i need a username to download it ,like this
Username for 'https://git.informatik.uni-hamburg.de': 
So, what should i do
thx

**Comment by sayantanauddy** [comment]
Hi,
Sorry for the error in the readme. This repo was migrated from an internal university repository and I forgot to update the links. Whereever you see https://git.informatik.uni-hamburg.... please replace this by https://github.com/sayantanauddy/hierarchical_bipedal_controller.git and I think it should work.

**Comment by xxx-007** [comment]
hi,I am very interested in your project，but i meet some questions.i cannot find  these two folders 'plots' and 'vrep_scenes'，so what should i do? Thank you very much!
![Uploading problem.jpg…]()
![Uploading plots.jpg…]()
![Uploading vrep_scenes.jpg…]()
